# Generated by Django 5.2.8 on 2026-09-24 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=24, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('team', models.CharField(max_length=80)),
                ('status', models.CharField(choices=[('open', 'Open'), ('over', 'Over budget'), ('archived', 'Archived')], default='open', max_length=12)),
                ('planned', models.DecimalField(decimal_places=2, max_digits=12)),
                ('actual', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='LineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.CharField(max_length=128)),
                ('action', models.CharField(max_length=48)),
                ('target', models.CharField(max_length=24)),
                ('detail', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ('-at',),
            },
        ),
    ]
