"""Render derived state into PROJECTIONS: the /hub.json snapshot, the state.json dict, and the
GENERATED .md docs. All read surfaces are rebuilt from here — never hand-maintained."""
import time

from . import ownership

GEN_BANNER = "<!-- GENERATED by hub_core from the event log; DO NOT EDIT. Change the entity + rebuild. -->"
_STATUS_GLYPH = {"todo": "[ ]", "active": "[~]", "in_progress": "[ ]", "blocked": "[!]", "done": "[x]", "dropped": "[-]", "shadow": "[s]"}


def _sorted(st, t):
    return sorted(st["by_type"].get(t, []), key=lambda e: e["id"])


def hub_snapshot(st, *, build, audit, generated_at=None, live=None) -> dict:
    """The canonical /hub.json payload the HTML renders FROM (single source of truth).

    Task rows are shallow-merged with their derived flags (deps_blocked/unblocked) and with the
    ownership the register resolves for them — owner role, collaborators, evidence, support,
    rollback and the INDEPENDENT verifier — for the view; the persisted entities remain
    schema-pure. Ownership is resolved here rather than stored, because the register's rules are
    the durable thing and the board gains tasks continuously.
    """
    flags = st.get("flags", {})
    task_bed = sorted(st.get("task_bed", st["by_type"].get("task", [])), key=lambda e: e["id"])
    tasks_view = ownership.decorate(
        [dict(t, **flags.get(t["id"], {})) for t in task_bed], ownership.load())
    return {
        "generated_at": generated_at if generated_at is not None else int(time.time()),
        "build": build,
        "audit": audit,
        "counts": st["counts"],
        "phases": st["phases"],
        "coverage": st["coverage"],
        "tasks": tasks_view,
        "adrs": _sorted(st, "adr"),
        "feats": _sorted(st, "feat"),
        "gaps": _sorted(st, "gap"),
        "caps": _sorted(st, "cap"),
        # Contracts downstream tasks cite by id in contract_refs. The DOCUMENT is the source of
        # truth; the entity exists so the cited id resolves to something (ember:task:0526).
        "contracts": _sorted(st, "contract"),
        "deploys": _sorted(st, "deploy"),
        # commits ride their own aggregate + type so the board FOLDS them (a count, not a feed row):
        # the activity rail whitelists task/adr/gap/feat/deploy/decision, so commit.recorded never
        # floods it, and the audit adapter turns an untasked commit into a firing check.
        "commits": _sorted(st, "commit"),
        "notes": _sorted(st, "note"),
        # Project-specific types (ADR-9). `findings`/`lessons` are generic; `methods` carries the
        # CHARTER §5 contributions (governance AND public content); `reviews` is the §4.3/§10.4
        # human gate — every T-3 derivation and R-class election passes through it, so an empty
        # audit log is only meaningful because this queue proves items went through one.
        "findings": _sorted(st, "finding"),
        "lessons": _sorted(st, "lesson"),
        "methods": _sorted(st, "method"),
        "reviews": _sorted(st, "review"),
        "graph": st["graph"],
        "dangling": st["dangling"],
        "live": live or {},
        "health": "bad" if not audit.get("ok") else ("warn" if not build.get("coherent", True) else "ok"),
    }


def state_json(st, *, build, audit, at=None) -> dict:
    """The machine state stamp. audit_ok + coherent are COMPUTED, never hand-set."""
    return {
        "repo_build": build.get("repo"),
        "last_deploy_build": build.get("deploy"),
        "last_deploy_tag": build.get("tag"),
        "last_deploy_sha": build.get("sha"),
        "served_sha": build.get("served_sha"),
        "coherent": build.get("coherent"),
        "last_audit_at": at or time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        "audit_ok": audit.get("ok"),
        "live_url": build.get("live_url"),
    }


def render_tasks_md(st) -> str:
    out = [GEN_BANNER, "# Tasks\n"]
    phases = {}
    tasks = sorted(st.get("task_bed", st["by_type"].get("task", [])), key=lambda e: e["id"])
    for t in tasks:
        phases.setdefault(t.get("phase") or "Unphased", []).append(t)
    for ph, rows in phases.items():
        out.append(f"\n## {ph}\n")
        out.append("| ID | Status | Pri | Title | Deps |")
        out.append("| --- | --- | --- | --- | --- |")
        for t in rows:
            g = _STATUS_GLYPH.get(t.get("status"), "[?]")
            out.append(f"| {t['id']} | {g} {t.get('status','')} | {t.get('priority','')} | {t.get('title','')} | {' '.join(t.get('deps') or [])} |")
    return "\n".join(out) + "\n"


def render_features_md(st) -> str:
    out = [GEN_BANNER, "# Features\n", "| ID | Status | Name | Tasks | Capability |", "| --- | --- | --- | --- | --- |"]
    for f in _sorted(st, "feat"):
        out.append(f"| {f['id']} | {f.get('status','')} | {f.get('name','')} | {' '.join(f.get('tasks') or [])} | {f.get('capability','')} |")
    return "\n".join(out) + "\n"


def render_adrs_md(st) -> str:
    out = [GEN_BANNER, "# Architecture Decision Records\n"]
    for a in _sorted(st, "adr"):
        out.append(f"\n## ADR {a.get('number','?')} — {a.get('title','')}  ({a.get('status','')})")
        if a.get("superseded_by"):
            out.append(f"_Superseded by: {' '.join(a['superseded_by'])}_")
        out.append(f"\n**Context**\n\n{a.get('context_md','')}\n\n**Decision**\n\n{a.get('decision_md','')}\n\n**Consequences**\n\n{a.get('consequences_md','')}")
        if a.get("amendments_md"):
            out.append(f"\n**Amendments**\n\n{a['amendments_md']}")
    return "\n".join(out) + "\n"


def render_deploys_md(st) -> str:
    out = [GEN_BANNER, "# Deploys (append-only)\n", "| At | Build | SHA | Method | audit_ok | served_sha |", "| --- | --- | --- | --- | --- | --- |"]
    for d in sorted(st["by_type"].get("deploy", []), key=lambda e: e.get("at", "")):
        out.append(f"| {d.get('at','')} | {d.get('build','')} | {d.get('sha','')} | {d.get('method','')} | {d.get('audit_ok','')} | {d.get('served_sha','')} |")
    return "\n".join(out) + "\n"


def render_changelog_md(st) -> str:
    """GENERATED changelog: deploy events newest-first + a shipped-feature summary. Doctrine sec2/13
    promise this as generated (never hand-maintained), so it can't drift from the event log."""
    out = [GEN_BANNER, "# Changelog\n", "_Generated from deploy events (newest first); do not edit._\n"]
    deploys = sorted(st["by_type"].get("deploy", []), key=lambda e: e.get("at", ""), reverse=True)
    if not deploys:
        out.append("_No deploys recorded yet._")
    for d in deploys:
        ok = "audit_ok ✓" if d.get("audit_ok") else "audit_ok ✗"
        served = (" · served `%s`" % d["served_sha"]) if d.get("served_sha") else ""
        out.append(f"\n## {d.get('build','?')} — {d.get('at','')}  ({ok})")
        out.append(f"- sha `{d.get('sha','')}`{served} · via {d.get('method','')}")
    shipped = sorted((f for f in st["by_type"].get("feat", []) if f.get("status") in ("shipped", "partial")),
                     key=lambda e: e["id"])
    if shipped:
        out.append("\n## Shipped features")
        for f in shipped:
            out.append(f"- **{f.get('name','')}** ({f.get('status')})")
    return "\n".join(out) + "\n"


def all_projections(st, *, build, audit) -> dict:
    """Everything to write to disk in a rebuild."""
    return {
        "state.json": state_json(st, build=build, audit=audit),
        "hub.json": hub_snapshot(st, build=build, audit=audit),
        "TASKS.md": render_tasks_md(st),
        "FEATURES.md": render_features_md(st),
        "ADR.md": render_adrs_md(st),
        "DEPLOYS.md": render_deploys_md(st),
        "CHANGELOG.md": render_changelog_md(st),
    }
